FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

COPY docker-entrypoint.dev.sh /usr/local/bin/docker-entrypoint.dev.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.dev.sh

EXPOSE 5000

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.dev.sh"]
